-- this script should be execute with the newly created USER
-- e.g.
--   sqlplus loyalty/Welcome_1@Alpha01A-DBCS.compute-gse00010885.oraclecloud.internal/pdb1.gse00010885.oraclecloud.internal \
--   @init-db.sql
-- if you are not sure with the service, just run lsnrctl status
--     remember to sudo su - oracle to run it

DROP TABLE customer;
DROP TABLE product;
DROP TABLE offers;

CREATE TABLE product
 (	"ID"            NUMBER NOT NULL ENABLE
 ,  "PRODUCTNAME"   VARCHAR2(255 BYTE)
 ,  "PRODUCTPRICE"  NUMBER
 ,  "PRODUCTIMAGE"  VARCHAR2(255 BYTE)
 ,  "PRODUCTDESC"   VARCHAR2(255 BYTE)
 ,  CONSTRAINT      "PRODUCT_PK" PRIMARY KEY ("ID")
 )
/

CREATE TABLE offers
 (	"ID"            NUMBER(*,0) NOT NULL ENABLE
 ,  "OFFERNAME"     VARCHAR2(255 BYTE)
 ,  "POINTS"        NUMBER(*,0)
 ,  "MESSAGE"       VARCHAR2(511 BYTE)
 ,  "PRODUCTID"     NUMBER
 ,  PRIMARY KEY ("ID")
 )
/

CREATE TABLE customer
  ( "ID"            NUMBER NOT NULL ENABLE
  , "CUSTOMERNAME"  VARCHAR2(255 BYTE)
  , "POINTS"        NUMBER(*,0)
  , "UNAME"         VARCHAR2(255 BYTE)
  ,                 PRIMARY KEY ("ID")
  )
/

COMMIT;

Insert into OFFERS (ID,OFFERNAME,POINTS,MESSAGE,PRODUCTID) values (10001,'Samsam Galaxy Offer',6000,'Exchange 6000 points for 10% discount of Samsam Mobile Phone',20001);
Insert into OFFERS (ID,OFFERNAME,POINTS,MESSAGE,PRODUCTID) values (10002,'iPhone 10',10000,'Exchange 10000 points for 20% dicount of iPhone 10',20002);
Insert into OFFERS (ID,OFFERNAME,POINTS,MESSAGE,PRODUCTID) values (10003,'Free Drinks',4000,'Exchange 500 points to get one free drink',20003);

Insert into PRODUCT (ID,PRODUCTNAME,PRODUCTPRICE,PRODUCTIMAGE,PRODUCTDESC) values (20001,'Samsam Galaxy 7',1000,'20001.jpg','The best Android phone in the galaxy');
Insert into PRODUCT (ID,PRODUCTNAME,PRODUCTPRICE,PRODUCTIMAGE,PRODUCTDESC) values (20002,'iPhone 10',1500,'20002.jpg','The phone comes from the future');
Insert into PRODUCT (ID,PRODUCTNAME,PRODUCTPRICE,PRODUCTIMAGE,PRODUCTDESC) values (20003,'Bear Beer',10,'20003.jpg','You cannot stop after the first pint');
COMMIT;

Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (30003,'Roland Dubois',4000,'roland.dubois');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (30001,'Lisa Jones',6000,'lisa.jones');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (30002,'Bala Gupta',10000,'bala.gupta');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40000,'Milton Caldwell',24912,'ebadi@ivpi.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40001,'Robert Ellis',33957,'oh@cepo.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40002,'Josephine Mendez',2293,'ide@sekkus.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40003,'Hattie Mason',43355,'rofacu@gesur.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40004,'Harry Thornton',3728,'ijehuh@gialvik.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40005,'Adeline Flores',48101,'pujan@fuhciseh.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40006,'Patrick Rowe',13912,'heisac@feukooto.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40007,'Daniel Reese',18736,'roktizawa@ic.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40008,'Tillie Allison',42396,'bocno@zegwifa.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40009,'Nettie Ortiz',16050,'uc@kojpeg.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40010,'Joseph Higgins',10747,'hog@pifu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40011,'Jane Luna',14025,'oz@kazbap.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40012,'Bettie Snyder',4682,'zu@ti.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40013,'Seth Vasquez',16798,'ja@sevuvku.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40014,'Millie Reynolds',32344,'ideapeiv@li.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40015,'Steve Schmidt',20419,'pisgohsu@jat.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40016,'Phoebe Martin',12428,'sir@nedku.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40017,'Thomas Ortiz',21542,'icwuw@ru.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40018,'Mabelle Tyler',15172,'wacsa@vodsa.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40019,'Brian Sutton',12613,'agsu@ineloh.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40020,'May Manning',16865,'awomo@iwo.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40021,'Alvin Hanson',47001,'wi@mugvevcal.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40022,'Christine Sanders',19962,'faczug@ufolobi.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40023,'Minerva Graham',25523,'tezam@guf.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40024,'Lilly Dixon',39058,'fufe@wutonhuf.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40025,'Richard Peters',12585,'hanevo@fu.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40026,'Henrietta Carson',28348,'becwoppa@mina.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40027,'Sean Oliver',30128,'big@sud.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40028,'Emilie McGuire',38947,'omen@as.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40029,'Edna Bishop',46112,'meuc@vocme.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40030,'Pearl Morgan',8504,'ofafe@vane.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40031,'Johnny Murphy',29800,'wimesle@jis.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40032,'Dollie Lawrence',20581,'dutma@heuj.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40033,'Theodore Tucker',1560,'piz@jeka.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40034,'Lora Rose',32491,'tedlem@tepteato.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40035,'Lois Wright',40879,'aca@vudembed.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40036,'Elijah McKinney',8474,'zinbeir@negjolek.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40037,'Michael Thomas',36454,'tamipup@kajho.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40038,'Rosalie Jenkins',49963,'dod@hethiimi.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40039,'Theresa Moran',11942,'ma@zamego.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40040,'Gertrude Stone',2135,'unigakwi@pu.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40041,'Mae Pearson',293,'tisniha@nadlit.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40042,'Belle Curry',39446,'iroitacet@hizholpo.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40043,'Stella Weaver',31969,'owifofwow@etocu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40044,'Thomas Carson',6617,'ob@awugol.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40045,'Jim Francis',33837,'bafi@jowiw.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40046,'Sara Delgado',49193,'ijpes@kad.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40047,'Hunter Stephens',247,'dabes@efubi.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40048,'Harvey Reeves',13185,'zu@saju.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40049,'Paul Vega',32603,'tavezvi@aluole.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40050,'Todd Warner',48858,'pijekafah@johpoaje.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40051,'Dorothy Vega',2071,'gur@hobhu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40052,'Glen Kim',39786,'onepunra@ijjuj.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40053,'Stella Rivera',13567,'fer@numiv.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40054,'Eugene Nichols',18422,'hige@ja.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40055,'Jesus Weber',22783,'egilur@gobufa.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40056,'Andre Flores',36758,'fabezo@do.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40057,'Laura Jordan',20979,'radav@vetizno.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40058,'Brian Mullins',7146,'tumicfi@ziwar.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40059,'Jason Norris',9927,'ta@ti.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40060,'Carrie Schneider',39355,'goder@docgun.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40061,'Madge Potter',33817,'hat@fajdu.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40062,'Lois Little',318,'mougi@zacoweli.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40063,'Anne Hansen',37756,'ves@be.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40064,'Warren Jones',44615,'nar@os.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40065,'Craig Greer',34205,'konguvov@jole.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40066,'Charles Rhodes',13331,'najitu@ditirtu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40067,'Juan Cole',44037,'natsi@dus.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40068,'Lina Cox',16971,'mivij@ciadlut.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40069,'Dollie Davidson',13329,'culoz@hatob.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40070,'Ethan Burke',27814,'awa@oliviema.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40071,'Danny Schmidt',7911,'barfu@latbahaba.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40072,'Tony Nelson',23347,'nakiabu@sego.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40073,'Lura Day',9914,'la@bo.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40074,'Dustin Robertson',9185,'niohwa@jensipu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40075,'Margaret McBride',48,'tujapveh@nu.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40076,'Zachary Carr',49868,'ipifi@kem.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40077,'Larry Ruiz',27675,'tukenla@jadlu.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40078,'Virgie Doyle',16515,'kozof@sovew.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40079,'Garrett Stone',38026,'li@cubfenav.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40080,'Willie Howard',6542,'igapuzucu@luw.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40081,'Lottie Ortega',49271,'ki@lobav.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40082,'Helena Wolfe',12019,'wusucesu@hunizbod.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40083,'Martin Warren',43059,'on@fasal.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40084,'Barbara Cortez',28364,'igiwmuz@uho.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40085,'Martin Bass',47014,'matudid@emcufmum.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40086,'Lewis Hill',1761,'hompopzuj@gajeg.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40087,'Nina Salazar',11060,'nagu@kohgo.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40088,'Clayton Simon',40761,'fuhjerwa@vunudece.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40089,'Carolyn Cohen',17224,'suckeb@cagmif.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40090,'Daniel Wagner',37477,'hak@sobalega.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40091,'Jerome Alvarado',35770,'dep@futcefmos.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40092,'Alvin Garner',43967,'nujvet@israwso.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40093,'Cecilia Shelton',13480,'tuvuhu@warimmep.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40094,'Russell Brock',16438,'nepiru@zovvero.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40095,'Mina Flores',185,'jojgi@basru.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40096,'Kathryn Hunter',37523,'hotacobe@nacoh.io');
commit;
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40097,'Ollie Wood',7032,'ib@sowam.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40098,'Rosa Snyder',39770,'cas@fubjor.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40099,'Bill Vega',24608,'tor@tag.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40100,'Lydia Long',34564,'to@sufasuna.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40101,'Christian Colon',519,'ovwaf@uniteno.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40102,'Rosie Simmons',38365,'ditefuku@cowtejun.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40103,'Ora McGuire',46840,'ujse@uzioruce.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40104,'Georgia Farmer',30322,'nennak@meedurum.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40105,'Tillie Saunders',34185,'luh@wa.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40106,'Ruth Foster',35000,'tuk@beve.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40107,'Jared Greene',14971,'ozpuje@boun.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40108,'Ronald Page',7502,'vacbava@wad.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40109,'Polly Bell',40473,'badumcu@lozcili.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40110,'Clayton Burke',44665,'comobep@sazfok.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40111,'Estella Stephens',46905,'ucno@iwuitizo.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40112,'Phoebe Brock',7449,'bejabi@ce.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40113,'Ophelia McDaniel',12930,'bi@hircavos.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40114,'Allen Cobb',20614,'leho@daiwnaf.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40115,'Fannie Page',4844,'urakuku@hebawod.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40116,'Virgie Black',25136,'hapsoje@runuw.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40117,'Joel Lindsey',37343,'ekevaju@kit.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40118,'Johnny Fuller',31921,'kivobo@wase.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40119,'Isabel Reynolds',25567,'mukaca@cutun.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40120,'Loretta Barker',3151,'jefu@feew.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40121,'Carolyn Paul',2837,'redocger@li.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40122,'Bruce Anderson',2503,'midpiho@meh.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40123,'Evelyn Wilson',20454,'culefuli@caevbih.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40124,'Jonathan Gutierrez',16740,'bo@sudwi.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40125,'Pearl Berry',24562,'ucvat@va.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40126,'Stephen Poole',13832,'vep@no.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40127,'Delia Kennedy',35472,'efuge@befej.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40128,'Bobby Lamb',42514,'ozgehbi@zaenbun.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40129,'Cecelia Caldwell',26701,'fid@ifobesa.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40130,'Danny Crawford',5928,'zen@ibtemoh.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40131,'Ray Stephens',31044,'ab@ra.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40132,'Lee Gutierrez',24585,'fumfop@jor.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40133,'Lewis Sparks',34936,'foz@ogawim.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40134,'Tom Roberson',3529,'nazoddo@va.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40135,'Stella Dean',37302,'wisba@tun.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40136,'Alta Gomez',17352,'el@ovzuvu.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40137,'Nettie Arnold',37594,'depi@dorcug.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40138,'Carolyn Coleman',12242,'lekjagti@ijo.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40139,'Bobby Osborne',11821,'ufo@pig.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40140,'Logan Morgan',3571,'desvajja@narcalwi.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40141,'Jean Gibbs',30317,'rownizde@rahi.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40142,'Ryan Rice',36613,'tocmumo@roc.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40143,'Derek Armstrong',26110,'muki@jad.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40144,'Katie Jimenez',2324,'eme@suzfum.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40145,'Dorothy McGuire',23146,'eviubuwe@jasta.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40146,'Emma Reyes',16290,'obafuiku@asamijo.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40147,'Helena Nash',88,'ot@je.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40148,'Ola Griffin',28526,'cunfipe@kehpuhog.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40149,'Mike Carr',6522,'nuk@pa.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40150,'Rosie Carson',9103,'tujke@suzajhov.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40151,'Inez Johnson',28754,'duzcur@itouwa.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40152,'Gabriel Watkins',42746,'doznu@tab.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40153,'Vernon Moore',28100,'vi@kubki.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40154,'Francisco Long',41632,'tevdaoc@daju.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40155,'Theodore Austin',9836,'vajdek@uv.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40156,'Cody Torres',28076,'woekore@todjubi.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40157,'Jayden Tyler',38087,'pamid@up.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40158,'Andre Anderson',12135,'resraljol@neehpun.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40159,'Jeremiah Alexander',33583,'mil@ar.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40160,'Jane Perkins',31914,'kokim@gar.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40161,'Aiden Floyd',40202,'cebuh@hac.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40162,'Herman Hill',2301,'ofrop@gagunrad.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40163,'Roy Craig',2931,'binedlin@didweuzo.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40164,'Ada May',11012,'rag@rip.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40165,'Lula Pratt',29018,'eg@ok.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40166,'Olivia Figueroa',10834,'gahipgul@migil.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40167,'Matthew Harvey',44787,'aleig@zapapajil.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40168,'Lois Santiago',39030,'uveva@gojuv.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40169,'Frederick Phelps',38997,'kapdecog@vo.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40170,'Lester Padilla',36695,'atkaz@dup.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40171,'Henrietta Campbell',22180,'nisunoos@juvomkut.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40172,'Daniel Bowman',25658,'mifco@izahuwvac.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40173,'Micheal Pena',10897,'hajdat@eb.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40174,'Estella Bowers',19603,'cepdavca@ma.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40175,'Glenn Osborne',30323,'ecro@ofomoc.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40176,'Lena Lane',35172,'fe@cokhi.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40177,'Lucy Kennedy',42240,'ruku@towomgu.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40178,'Hallie Baker',42156,'sevju@was.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40179,'Derek Harrington',34002,'lappok@tadku.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40180,'Victor Sanchez',2862,'vouj@zet.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40181,'Maria Lynch',16208,'ho@wetub.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40182,'Dominic Hayes',6994,'mu@ime.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40183,'Herman Vargas',25216,'lesfejaw@koweek.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40184,'Lettie Reese',6046,'gassais@jolumip.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40185,'Carl Graham',36267,'riscaj@ewadezu.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40186,'Augusta Brown',44974,'kategmu@negjid.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40187,'Peter Lyons',37517,'isji@jo.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40188,'Katie French',12872,'ram@picasguv.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40189,'Eleanor Maxwell',11342,'fad@ebase.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40190,'Derek Hernandez',156,'ezi@ul.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40191,'Erik Lambert',24899,'wile@pat.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40192,'Kenneth Joseph',44358,'nakic@nevonoc.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40193,'Mary Wilkerson',20364,'eg@noh.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40194,'Nannie Kennedy',19628,'bagowu@zazfif.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40195,'Louisa Wallace',41550,'emu@poowja.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40196,'Clarence Wells',37607,'resuwah@niw.co.uk');
commit;
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40197,'Travis Neal',26602,'bifzornus@orvuov.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40198,'Clarence Haynes',17271,'ivki@nim.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40199,'Lelia Schneider',47863,'ha@ho.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40200,'Olga Stewart',20564,'uhju@cahoari.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40201,'Adam Wolfe',8623,'wusirar@gacco.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40202,'Alta Erickson',23972,'tagma@senrehfe.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40203,'Alfred Hardy',44337,'ora@pit.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40204,'Jeff Maldonado',21776,'hadrocas@mopug.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40205,'Viola Holland',23951,'jupic@ul.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40206,'Estella Morrison',41143,'mozod@cah.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40207,'Don Clayton',4692,'ufsirav@jedwov.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40208,'Clara Moreno',8980,'ibunalhoj@jep.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40209,'Clifford Leonard',14185,'pifmib@sigej.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40210,'Emily Gutierrez',28677,'daekaf@sefa.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40211,'Alice Long',37185,'fu@kievzut.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40212,'Michael Barnes',26937,'hackihal@tuz.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40213,'Keith Poole',16005,'jo@lu.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40214,'Delia Bryan',502,'tak@megjep.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40215,'Shane Rhodes',19753,'oladeb@zirveili.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40216,'Jim Rhodes',49434,'pifob@solce.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40217,'Ola Jennings',41830,'cizoud@tarfaruce.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40218,'Elmer Williamson',44535,'hudinsuz@delaom.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40219,'Derek Mitchell',15894,'kafhedof@jof.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40220,'Essie Phelps',38596,'duhirna@potsip.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40221,'Gabriel Paul',23892,'ke@dik.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40222,'Zachary Rios',15989,'puzi@ca.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40223,'Logan Foster',27253,'lamzoh@bogni.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40224,'Harriett Watts',30238,'ti@waeg.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40225,'Tony Schwartz',12026,'ce@inwir.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40226,'Katherine Cook',41350,'zafo@was.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40227,'Vincent Walsh',40325,'vo@ag.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40228,'Gene Carroll',22689,'ko@bihtubduf.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40229,'Myrtie Henry',27941,'ep@jiccer.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40230,'Mason Vargas',24895,'cizno@nufpov.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40231,'Bruce Alexander',25511,'gukrote@foiloven.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40232,'Eleanor Washington',19733,'misughu@luj.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40233,'Earl Schneider',48887,'ro@idgufaz.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40234,'Mina Reeves',17491,'pi@efhotoji.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40235,'Jennie Warren',35009,'omo@vofzir.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40236,'Violet Harmon',30987,'hi@mukeperob.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40237,'Jimmy Garza',9141,'relra@nej.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40238,'Harvey Green',48111,'nilijowak@ece.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40239,'Sallie McBride',16780,'ko@udraafo.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40240,'Grace Bishop',4455,'ru@lap.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40241,'Delia Long',17411,'focim@cetvuin.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40242,'Christian Reed',16071,'enjarep@ejocifup.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40243,'Sean Casey',8230,'cemutga@ejoitokol.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40244,'Alta Harris',27777,'mifi@lifbor.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40245,'Charlotte Clarke',3599,'aldub@zujog.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40246,'Cody Lawrence',17109,'usebogji@cehhoda.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40247,'Duane Blake',25306,'keano@une.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40248,'Alma Frank',21749,'cecbukaw@zov.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40249,'Mae Dunn',11329,'gujvope@ado.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40250,'Ray Fisher',18611,'hefos@kizotar.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40251,'Dylan Atkins',36530,'fon@zaedo.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40252,'Christopher Knight',49367,'lahep@saf.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40253,'Aiden Harrington',48100,'pajes@afi.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40254,'Johanna Robbins',33083,'vil@jigsubtak.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40255,'Bill Todd',27625,'kap@usbajpif.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40256,'Sally Dawson',11063,'evate@fik.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40257,'Victor Brady',45422,'for@sa.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40258,'Stephen Holland',8255,'rotir@herako.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40259,'John Townsend',32110,'wiac@dumdu.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40260,'Roy Luna',1702,'enlu@sagfofkug.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40261,'Isabel Harrington',29116,'se@vujde.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40262,'Ronald Watts',38707,'sekik@dep.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40263,'Hunter Rodriguez',47136,'rohanpi@vepikal.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40264,'Eleanor Allen',40900,'losek@juozi.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40265,'Alex Norton',15006,'diz@zab.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40266,'Maud Mason',9029,'ahwu@salzut.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40267,'Sarah Nash',35251,'toto@ban.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40268,'Rosa Poole',21204,'jaletur@uh.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40269,'Mabelle Martin',3142,'polus@waazovag.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40270,'Jay Sutton',1380,'ih@owibo.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40271,'Alfred Tate',40715,'wuntev@fukdisice.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40272,'Bruce Roberson',35464,'viwjojat@davwi.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40273,'Hattie Day',32477,'pabulan@kede.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40274,'Leo Bradley',42062,'dohim@dikpidpar.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40275,'Bertha Montgomery',29002,'ucauhe@jisarju.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40276,'Micheal Cummings',3410,'mapbo@mucgewdo.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40277,'Ivan Terry',43860,'farur@cep.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40278,'Jose Salazar',46379,'fa@tabjomir.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40279,'Jack Quinn',40704,'ode@tilso.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40280,'Anne Caldwell',7180,'ignutduf@tium.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40281,'Olive Hayes',30446,'javrah@ujdaneri.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40282,'Lucinda Porter',37031,'tifwiwa@bovisad.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40283,'Marcus Harrison',16196,'tac@vavam.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40284,'Connor Hawkins',15813,'etpa@capfo.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40285,'Lillie Beck',16810,'wij@akowe.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40286,'Madge Pratt',5484,'lidikic@vif.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40287,'Jane Thomas',3252,'wurge@pa.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40288,'Theresa Dixon',2681,'nus@paz.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40289,'Mamie Wolfe',3658,'lici@ziruna.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40290,'Patrick Clayton',32445,'az@isali.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40291,'Mike Ramsey',20359,'tap@mewvoso.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40292,'Annie Page',37496,'jilulzir@wikfe.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40293,'Lucy Ortiz',37928,'sut@lannojoha.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40294,'Flora Yates',36486,'pe@law.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40295,'Nina Underwood',28456,'funuvu@ute.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40296,'Jayden Ryan',17569,'ba@ri.com');
commit;
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40297,'Julian Rivera',17170,'sep@zevnuv.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40298,'Derrick Goodwin',11074,'zowo@adavuszij.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40299,'Christine Quinn',1930,'fakab@tup.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40300,'Blanche Moreno',41575,'redwo@me.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40301,'Jeanette Woods',20151,'li@coptu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40302,'Delia Burns',12513,'duturewaf@orvih.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40303,'Randy Roberts',22869,'hajit@epgabo.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40304,'Terry Sanders',36997,'hu@kuja.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40305,'Jordan Stone',42366,'nuj@eze.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40306,'Eva Guzman',15070,'wasdaz@ce.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40307,'Chester Barton',2694,'hikohcu@jid.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40308,'Olive Wright',11044,'dotlega@ifa.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40309,'Julia Gross',14974,'ifdicgi@pa.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40310,'Essie Todd',23094,'guj@kujez.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40311,'Alexander Carter',37057,'oginamsi@nofcof.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40312,'Gene Holt',23926,'tapid@kokvero.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40313,'Nathan Romero',17161,'he@sira.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40314,'Blake Horton',32532,'cew@nol.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40315,'Tony Gibbs',390,'atmeono@upa.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40316,'Rhoda Sims',29270,'zunga@ke.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40317,'Nathaniel Walters',36146,'mokoobo@vi.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40318,'Dustin Burton',35927,'lasjoc@eh.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40319,'Lucinda Flores',45773,'tomerto@niodooho.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40320,'Clara Weaver',9912,'efuwoun@holru.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40321,'Jane Stewart',18327,'hu@te.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40322,'Dollie Cohen',34379,'kidzelwo@gomigu.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40323,'Sally Gibbs',27458,'nugurosa@oh.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40324,'Sallie Schneider',45696,'ofahi@mofotu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40325,'Alvin Vaughn',3542,'vot@te.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40326,'Virgie Johnston',2212,'rotaove@norgep.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40327,'Lloyd Robertson',35060,'wew@pisunop.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40328,'Nathaniel Owen',31740,'dudfa@he.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40329,'Millie Lloyd',44039,'rotged@vuciw.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40330,'Kathryn Harrington',7060,'ruv@la.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40331,'Laura Buchanan',35333,'minno@ir.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40332,'Ollie Lane',5523,'toblat@rahudsuh.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40333,'Bryan Rice',25951,'akuifemar@jijir.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40334,'Cecelia Chavez',26084,'ahi@asrif.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40335,'Brett Adkins',15767,'rad@lujne.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40336,'Tom Ford',41739,'rewud@dilconon.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40337,'Jay Willis',43626,'zeri@mebal.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40338,'Hallie Phelps',49195,'dufzaid@vahosre.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40339,'Jesus Valdez',5173,'bowfel@peruc.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40340,'Blanche Summers',27477,'tu@rekios.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40341,'Caroline Castro',7626,'etivol@awumac.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40342,'Charles Murphy',20405,'rirmopin@kosmif.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40343,'Angel Nunez',9520,'nerfig@re.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40344,'Nora Horton',7653,'mu@hiwliz.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40345,'Virginia Cole',15532,'cuukoar@uku.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40346,'Blanche Stevens',43829,'lacemu@joc.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40347,'Willie Maxwell',48397,'zehuwbim@bu.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40348,'Tillie Wallace',28125,'fer@ij.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40349,'Melvin Jordan',39825,'ano@tojakku.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40350,'Troy Baker',23700,'iki@oh.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40351,'Bertie Day',13946,'venli@udu.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40352,'Oscar Franklin',16055,'vennef@lakothof.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40353,'Winifred Sparks',9822,'fis@bowkuk.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40354,'Chad Gomez',17668,'jolta@nu.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40355,'Mark Reeves',1481,'tamoce@fijab.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40356,'Lettie Hodges',5224,'sez@ap.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40357,'Jordan Schwartz',7055,'oseuho@ip.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40358,'Barry Barber',22047,'uk@iguve.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40359,'Hilda Parsons',15590,'kabgighe@sapwe.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40360,'Bertha Pratt',23345,'eke@galugfa.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40361,'Frank Gibson',39642,'hufacmim@tik.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40362,'Alta Walsh',49749,'zomlud@rabfig.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40363,'Sophia Lambert',10558,'milneohi@isi.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40364,'Cornelia Wolfe',19599,'eg@heikizu.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40365,'Travis Clarke',40706,'saacizov@no.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40366,'Hilda Tran',5985,'na@gin.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40367,'Florence Tran',16269,'az@dous.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40368,'Mae Perkins',7996,'odu@cu.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40369,'Rosetta Jackson',47939,'misob@ze.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40370,'Clarence Owen',7098,'zupod@ur.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40371,'Raymond Sutton',18105,'gagwat@la.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40372,'Don Aguilar',15928,'pil@po.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40373,'Lydia Fisher',38533,'ha@ermed.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40374,'Isabella Horton',43636,'reri@gapiko.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40375,'Robert Sutton',30796,'lupuh@metgal.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40376,'Melvin Weaver',2765,'uzjalboz@pitcuer.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40377,'Olive Wright',15051,'kiska@ho.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40378,'Estella Norris',2757,'ci@febat.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40379,'Carolyn McGee',42247,'ba@ivo.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40380,'Patrick Edwards',30353,'peuru@cius.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40381,'Carrie Alvarado',13869,'sifmi@zeppa.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40382,'Lettie Butler',942,'imjuh@mik.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40383,'Katharine Hicks',4741,'tivkoza@tuwesbe.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40384,'Owen Hodges',19334,'agdup@gos.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40385,'Gary Hale',2439,'ik@jusec.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40386,'Ophelia Douglas',48633,'jej@li.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40387,'Lewis Cain',880,'we@kurarla.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40388,'Rosalie Hawkins',23554,'ne@rekikpo.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40389,'Emma Drake',14167,'unut@ip.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40390,'Barry Hines',20164,'iju@pirohge.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40391,'Ethel Park',20080,'mipla@bure.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40392,'Shawn Hart',23207,'ruka@jenwa.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40393,'Rhoda Ortega',21633,'bihsowki@cakbepo.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40394,'Sam Lamb',20770,'dumaru@oba.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40395,'Hester Guzman',19392,'vilwa@ti.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40396,'Luella Bryan',37245,'firlag@muv.co.uk');
commit;
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40397,'Daisy Brady',1503,'bi@bozu.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40398,'Peter Holt',19431,'weabliz@mucvukhe.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40399,'Chad Elliott',23124,'fu@lanbe.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40400,'Steven Patton',15665,'be@pac.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40401,'Oscar Lee',30258,'sesooda@mocug.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40402,'Tyler Aguilar',17416,'bo@igmi.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40403,'Helena Cohen',29047,'los@ular.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40404,'Adele Castro',20419,'zenres@ger.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40405,'Isabella Estrada',24363,'nimiar@lofatuvaj.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40406,'Leona Hammond',20817,'ovvavwu@me.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40407,'Manuel Castro',31071,'norvif@zegser.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40408,'Henry Sutton',15835,'tun@ce.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40409,'Tommy Gibson',29761,'hez@poho.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40410,'Hettie Leonard',20779,'go@gendu.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40411,'Landon Maxwell',21977,'beh@haf.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40412,'Darrell Lewis',48778,'posalfa@nubalo.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40413,'Lura Hayes',7254,'ehefa@hudbepwej.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40414,'Peter Hampton',35927,'hew@esoed.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40415,'Paul Cohen',10660,'cibdeh@wawvewzoz.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40416,'Carlos Lane',40443,'ritul@vospolob.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40417,'Lettie Gonzales',47296,'upule@ihkelob.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40418,'Carrie Curry',12783,'vod@ahwig.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40419,'Callie Barnes',18260,'su@du.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40420,'Winifred Peterson',25113,'mi@estaz.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40421,'Jack Hammond',37645,'sen@gir.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40422,'Frances Stewart',38359,'sivtava@vefah.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40423,'Eliza Brock',823,'ta@wi.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40424,'Ernest Rodgers',29581,'zivuf@da.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40425,'Norman Sharp',1610,'efeiji@kibmilmor.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40426,'Lloyd Pierce',13904,'owi@oduikiwuz.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40427,'Fanny Holloway',2546,'pegbafod@tuzivoju.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40428,'Fanny Lawrence',35162,'sug@mocsuj.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40429,'Katie Owen',11987,'guzed@ku.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40430,'Elsie Evans',47369,'huvcig@ihi.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40431,'Peter Alvarado',27374,'biwurijo@ranwiv.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40432,'Tommy Medina',44497,'fel@gen.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40433,'Ian Owens',45686,'mi@asebih.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40434,'Alan Higgins',16631,'coajosug@vetid.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40435,'Lizzie Huff',44224,'usueru@amaci.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40436,'Johanna Walton',13151,'huiwomos@wap.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40437,'Sue Williamson',34227,'go@rawasa.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40438,'May Armstrong',48221,'puuw@ti.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40439,'Edwin Garza',16009,'wum@uktawud.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40440,'Eleanor Romero',43144,'ogeatiuhe@otu.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40441,'Jerome Erickson',20336,'olekeceri@tobif.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40442,'Sara Barnett',35626,'ti@kuloj.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40443,'Cecilia George',5487,'gujtugbuc@zes.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40444,'George Perry',38903,'pa@zicube.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40445,'Richard Morrison',1236,'popdofpe@urbe.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40446,'Justin Bates',2854,'nut@faf.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40447,'Sara Hines',12677,'zos@fu.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40448,'Hester Nash',36910,'ot@lu.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40449,'Ann Blake',41456,'awta@gopi.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40450,'Hunter Thompson',24048,'fuvib@nuk.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40451,'Martha Garza',2721,'opehawoc@renu.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40452,'Angel Wells',3454,'vogfioje@towkeno.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40453,'Jared Martin',28425,'mi@pawca.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40454,'Bryan Berry',47610,'rizicmop@vatuwi.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40455,'Elmer Malone',29754,'hurecfol@hagumo.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40456,'Peter Sparks',23306,'lasukde@delose.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40457,'Maud Lambert',11975,'bapior@ukeagi.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40458,'Sam Snyder',40857,'ez@su.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40459,'Fred Buchanan',39471,'celuf@gisdo.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40460,'David Boyd',25056,'zumalja@hemzu.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40461,'Derek Foster',21433,'sas@rokal.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40462,'Edwin Hayes',41338,'laj@isnum.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40463,'Effie Carter',16561,'cofnun@cohda.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40464,'Joe Thomas',472,'fokdihek@zurehdu.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40465,'Eric Mills',14116,'je@voslebol.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40466,'Maurice Salazar',26130,'uja@vo.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40467,'Irene Brock',21331,'mibho@fimesika.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40468,'Zachary Pittman',45988,'ivo@ihgofub.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40469,'Antonio Bowers',46500,'ok@we.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40470,'Agnes Hudson',30544,'mepfokkom@ret.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40471,'Wesley Soto',39829,'olkol@kin.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40472,'Tyler Bass',15640,'osivak@toiti.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40473,'Elva Miles',36175,'omla@nunnub.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40474,'Caleb Torres',10744,'jokuwfak@hoz.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40475,'Vincent Jacobs',26728,'zuwcem@zobmofah.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40476,'Celia Ortega',13677,'go@sombev.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40477,'Linnie Nguyen',49116,'ivlag@sahaz.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40478,'Caleb Shelton',30952,'ihuwan@uvepuj.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40479,'Eugenia Conner',49361,'aha@amci.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40480,'Isabel Payne',42734,'noerazev@if.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40481,'Joe Santiago',29101,'itejulo@vosju.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40482,'Agnes Curry',20871,'wehetowa@toj.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40483,'Roxie Hernandez',38588,'fe@ekezoet.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40484,'Lulu Russell',27323,'sufebvi@dimejofoz.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40485,'Curtis Newton',38828,'fedimfum@hihlim.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40486,'Isabella Berry',6701,'pijih@javlewigu.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40487,'Rachel Rhodes',40244,'vake@uj.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40488,'Trevor French',13764,'owo@sowcef.io');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40489,'Samuel Rogers',17141,'idetac@caka.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40490,'Johnny Bates',6912,'ude@cemgod.edu');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40491,'Cody Lowe',34177,'heefe@sodemte.com');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40492,'Ethel Hicks',48952,'si@wudej.net');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40493,'Caleb McBride',19468,'pa@mokunuco.org');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40494,'Cordelia Jensen',44571,'obri@nim.co.uk');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40495,'Ophelia Young',37442,'uvulat@dobbif.gov');
Insert into customer (ID,CUSTOMERNAME,POINTS,UNAME) values (40496,'Francis Todd',34274,'zuni@wavrib.edu');
commit;

exit;
